baseurl = "https://magic-lantern.github.io/"
title = "Seth Russell"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = "UA-127048637-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# thanks to https://randomgeekery.org/2017/09/15/full-content-hugo-feeds/ and https://coolbutuseless.bitbucket.io/2018/02/07/blogdown-rss-feed-of-full-articles/
rssLimit = 10

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = false
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Seth Russell"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Seth Russell"
    description = "informatics, software engineering, data science, and healthcare research blog"
    github = "https://github.com/magic-lantern"
    linkedin = "https://www.linkedin.com/in/seth-russell"
    twitter = "https://twitter.com/magic__lantern"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "/page/cv"
    weight = 4